version: '3'
services:
  server:
    build:
      dockerfile: '../containers/server/Dockerfile'
      context: './server'
    container_name: movie-picks_server
    command: bash -c "bundle exec rails s -b 0.0.0.0"
    environment:
      RAILS_ENV: 'development'
      TZ: "Asia/Tokyo"
    ports:
      - "3000:3000"
    volumes:
      - ./server/:/home/moviepicks/project/

  db:
    image: mysql:5.7
    container_name: movie-picks_db
    environment:
      MYSQL_DATABASE: 'moviepicks_development'
      MYSQL_ROOT_PASSWORD: 'password'
      TZ: "Asia/Tokyo"
    volumes:
      - ./containers/db/my.cnf:/etc/mysql/my.cnf
      - db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db:
