version: '3.7'

x-template: &rails
  build:
    dockerfile: ../containers/server/Dockerfile
    context: ./server
  volumes:
    - /home/moviepicks/project/tmp
    - ./server/:/home/moviepicks/project/

services:
  server: 
    <<: *rails
    container_name: moviepicks_server
    command: bash -c "bundle exec rails s -b 0.0.0.0"
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
      - worker

  worker:  
    <<: *rails
    container_name: moviepicks_worker
    command: bash -c "bundle exec sidekiq"
    depends_on:
      - db
      - redis

  db:
    image: mysql:5.7
    container_name: moviepicks_db
    environment:
      MYSQL_DATABASE: moviepicks_development
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ./containers/db/my.cnf:/etc/mysql/my.cnf
      - db:/var/lib/mysql

  redis:
    image: redis:5.0.4
    container_name: moviepicks_redis

volumes:
  db:
