version: 2.1
orbs:
  ruby-orbs: sue445/ruby-orbs@1.4.3
  docker: circleci/docker@0.5.13

executors:
  server:
    docker:
      - image: circleci/ruby:2.6.5
      - image: circleci/mysql:5.7-ram
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
        environment:
          MYSQL_ROOT_PASSWORD: 'password'
    working_directory: ~/project/server
    environment: 
      RAILS_ENV: 'test'
      DATABASE_HOST: 127.0.0.1
      TZ: "Asia/Tokyo"
  frontend:
    docker:
      - image: circleci/node:8.11.4
    working_directory: ~/project/client
    environment: 
      TZ: "Asia/Tokyo"

jobs:
  rspec:
    executor: 
      name: server
    steps:
      - checkout:
          path: ~/project
      - ruby-orbs/bundle-install:
          restore_bundled_with: false
          cache_key_prefix: v2-bundle
      - run: bundle exec rake db:create db:schema:load
      - run: mkdir ~/rspec
      - run: bundle exec rspec --profile 10 --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
      - store_test_results:
          path: ~/rspec
      - store_artifacts:
          path: ~/project/server/coverage

workflows:
  test_and_build-image:
    jobs:
      - rspec
      - docker/publish:
          filters:
            branches:
              only:
                - master
          requires:
            - rspec
          image: ogontaro/moviepicks-server
          path: ~/project/server
          dockerfile: ../containers/server/production/Dockerfile 
      - docker/publish:
          filters:
            branches:
              only:
                - master
          requires:
            - rspec
          image: ogontaro/moviepicks-worker
          path: ~/project/server
          dockerfile: ../containers/server/production/Dockerfile 

