version: 2.1
orbs:
  ruby-orbs: sue445/ruby-orbs@1.4.3
executors:
  server:
    working_directory: ~/server
    docker:
      - image: circleci/ruby:2.5.3
    environment: 
      RAILS_ENV: 'test'
      TZ: "Asia/Tokyo"
  frontend:
    working_directory: ~/client
    docker:
      - image: circleci/node:8.11.4
    environment: 
      TZ: "Asia/Tokyo"

jobs:
  test_server:
    executor: 
      name: server
    steps:
      - checkout
      - ruby-orbs/bundle-install
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      - run: bundle exec rspec

workflows:
  test_and_build:
    jobs:
      - test_server
