version: 2.1
orbs:
  ruby-orbs: sue445/ruby-orbs@1.4.3

executors:
  server:
    docker:
      - image: circleci/ruby:2.6.3
      - image: circleci/mysql:5.7-ram
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
        environment:
          MYSQL_ROOT_PASSWORD: 'password'
    working_directory: ~/project/server
    environment: 
      RAILS_ENV: 'test'
      DATABASE_HOST: 127.0.0.1
      TZ: "Asia/Tokyo"
      REVIEWDOG_VERSION: 0.9.11
  frontend:
    docker:
      - image: circleci/node:8.11.4
    working_directory: ~/project/client
    environment: 
      TZ: "Asia/Tokyo"

jobs:
  rubocop:
    executor: 
      name: server
    steps:
      - checkout:
          path: ~/project
      - ruby-orbs/bundle-install:
          restore_bundled_with: false
      - run:
          name: Install reviewdog
          command: curl -fSL https://github.com/haya14busa/reviewdog/releases/download/$REVIEWDOG_VERSION/reviewdog_linux_amd64 -o reviewdog && chmod +x ./bin/reviewdog
      # - run: curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s
      - run: bundle exec rubocop | ./bin/reviewdog -f=rubocop -diff="git diff origin/master"

  test_server:
    executor: 
      name: server
    steps:
      - checkout:
          path: ~/project
      - ruby-orbs/bundle-install:
          restore_bundled_with: false
      - run: bundle exec rake db:create db:schema:load
      - run: mkdir ~/rspec
      - run: bundle exec rspec --format progress --format RspecJunitFormatter -o ~/rspec/rspec.xml
      - store_test_results:
          path: ~/rspec

workflows:
  lint_and_test:
    jobs:
      - rubocop
      - test_server
