apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels: 
      service: redis
      env: production
  template:
    metadata:
      labels:
        service: redis
        env: production
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
