apiVersion: v1
kind: Service
metadata:
  name: production-redis
spec:
  type: ClusterIP
  ports:
    - name: "redis-port"
      protocol: "TCP"
      port: 6379
      targetPort: 6379
  externalIPs:
    - 192.168.18.161
  selector: 
    service: redis
    env: production
